In [17]:
import sys

print(sys.executable)

/home/natha/Projetos/projetoAnalista/mortgage-analytics/.venv/bin/python

In [18]:
import pandas as pd

In [19]:
df = pd.read_csv("../data/raw/hmda_2024_florida.csv")

/tmp/ipykernel_9132/2301974922.py:1: DtypeWarning: Columns (22: loan_to_value_ratio, 23: interest_rate, 24: rate_spread, 26: total_loan_costs, 27: total_points_and_fees, 28: origination_charges, 29: discount_points, 30: lender_credits, 31: loan_term, 32: prepayment_penalty_term, 33: intro_rate_period, 38: property_value, 43: total_units, 44: multifamily_affordable_units, 46: debt_to_income_ratio, 77: applicant_age, 78: co-applicant_age, 79: applicant_age_above_62, 80: co-applicant_age_above_62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/hmda_2024_florida.csv")

In [20]:
df.columns.tolist()

['activity_year',
 'lei',
 'derived_msa-md',
 'state_code',
 'county_code',
 'census_tract',
 'conforming_loan_limit',
 'derived_loan_product_type',
 'derived_dwelling_category',
 'derived_ethnicity',
 'derived_race',
 'derived_sex',
 'action_taken',
 'purchaser_type',
 'preapproval',
 'loan_type',
 'loan_purpose',
 'lien_status',
 'reverse_mortgage',
 'open-end_line_of_credit',
 'business_or_commercial_purpose',
 'loan_amount',
 'loan_to_value_ratio',
 'interest_rate',
 'rate_spread',
 'hoepa_status',
 'total_loan_costs',
 'total_points_and_fees',
 'origination_charges',
 'discount_points',
 'lender_credits',
 'loan_term',
 'prepayment_penalty_term',
 'intro_rate_period',
 'negative_amortization',
 'interest_only_payment',
 'balloon_payment',
 'other_nonamortizing_features',
 'property_value',
 'construction_method',
 'occupancy_type',
 'manufactured_home_secured_property_type',
 'manufactured_home_land_property_interest',
 'total_units',
 'multifamily_affordable_units',
 'income',
 'debt_to_income_ratio',
 'applicant_credit_score_type',
 'co-applicant_credit_score_type',
 'applicant_ethnicity-1',
 'applicant_ethnicity-2',
 'applicant_ethnicity-3',
 'applicant_ethnicity-4',
 'applicant_ethnicity-5',
 'co-applicant_ethnicity-1',
 'co-applicant_ethnicity-2',
 'co-applicant_ethnicity-3',
 'co-applicant_ethnicity-4',
 'co-applicant_ethnicity-5',
 'applicant_ethnicity_observed',
 'co-applicant_ethnicity_observed',
 'applicant_race-1',
 'applicant_race-2',
 'applicant_race-3',
 'applicant_race-4',
 'applicant_race-5',
 'co-applicant_race-1',
 'co-applicant_race-2',
 'co-applicant_race-3',
 'co-applicant_race-4',
 'co-applicant_race-5',
 'applicant_race_observed',
 'co-applicant_race_observed',
 'applicant_sex',
 'co-applicant_sex',
 'applicant_sex_observed',
 'co-applicant_sex_observed',
 'applicant_age',
 'co-applicant_age',
 'applicant_age_above_62',
 'co-applicant_age_above_62',
 'submission_of_application',
 'initially_payable_to_institution',
 'aus-1',
 'aus-2',
 'aus-3',
 'aus-4',
 'aus-5',
 'denial_reason-1',
 'denial_reason-2',
 'denial_reason-3',
 'denial_reason-4',
 'tract_population',
 'tract_minority_population_percent',
 'ffiec_msa_md_median_family_income',
 'tract_to_msa_income_percentage',
 'tract_owner_occupied_units',
 'tract_one_to_four_family_homes',
 'tract_median_age_of_housing_units']

In [21]:
df.head()

,activity_year,lei,derived_msa-md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason-2,denial_reason-3,denial_reason-4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2024,IUGPUX5LWRZ3B6KIZ697,27260,FL,12031.0,1.203101e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,15930,43.12,98000,127,3993,4562,12
1,2024,IUGPUX5LWRZ3B6KIZ697,99999,FL,12107.0,1.210795e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,6134,41.10,66100,81,1653,2566,48
2,2024,IUGPUX5LWRZ3B6KIZ697,27260,FL,12109.0,1.210902e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,7012,12.36,98000,121,2147,2927,23
3,2024,IUGPUX5LWRZ3B6KIZ697,27260,FL,12031.0,1.203101e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,9862,45.96,98000,119,2667,3249,17
4,2024,IUGPUX5LWRZ3B6KIZ697,27260,FL,12031.0,1.203102e+10,C,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,4901,39.95,98000,82,605,964,34

In [22]:
df.columns.tolist()

['activity_year',
 'lei',
 'derived_msa-md',
 'state_code',
 'county_code',
 'census_tract',
 'conforming_loan_limit',
 'derived_loan_product_type',
 'derived_dwelling_category',
 'derived_ethnicity',
 'derived_race',
 'derived_sex',
 'action_taken',
 'purchaser_type',
 'preapproval',
 'loan_type',
 'loan_purpose',
 'lien_status',
 'reverse_mortgage',
 'open-end_line_of_credit',
 'business_or_commercial_purpose',
 'loan_amount',
 'loan_to_value_ratio',
 'interest_rate',
 'rate_spread',
 'hoepa_status',
 'total_loan_costs',
 'total_points_and_fees',
 'origination_charges',
 'discount_points',
 'lender_credits',
 'loan_term',
 'prepayment_penalty_term',
 'intro_rate_period',
 'negative_amortization',
 'interest_only_payment',
 'balloon_payment',
 'other_nonamortizing_features',
 'property_value',
 'construction_method',
 'occupancy_type',
 'manufactured_home_secured_property_type',
 'manufactured_home_land_property_interest',
 'total_units',
 'multifamily_affordable_units',
 'income',
 'debt_to_income_ratio',
 'applicant_credit_score_type',
 'co-applicant_credit_score_type',
 'applicant_ethnicity-1',
 'applicant_ethnicity-2',
 'applicant_ethnicity-3',
 'applicant_ethnicity-4',
 'applicant_ethnicity-5',
 'co-applicant_ethnicity-1',
 'co-applicant_ethnicity-2',
 'co-applicant_ethnicity-3',
 'co-applicant_ethnicity-4',
 'co-applicant_ethnicity-5',
 'applicant_ethnicity_observed',
 'co-applicant_ethnicity_observed',
 'applicant_race-1',
 'applicant_race-2',
 'applicant_race-3',
 'applicant_race-4',
 'applicant_race-5',
 'co-applicant_race-1',
 'co-applicant_race-2',
 'co-applicant_race-3',
 'co-applicant_race-4',
 'co-applicant_race-5',
 'applicant_race_observed',
 'co-applicant_race_observed',
 'applicant_sex',
 'co-applicant_sex',
 'applicant_sex_observed',
 'co-applicant_sex_observed',
 'applicant_age',
 'co-applicant_age',
 'applicant_age_above_62',
 'co-applicant_age_above_62',
 'submission_of_application',
 'initially_payable_to_institution',
 'aus-1',
 'aus-2',
 'aus-3',
 'aus-4',
 'aus-5',
 'denial_reason-1',
 'denial_reason-2',
 'denial_reason-3',
 'denial_reason-4',
 'tract_population',
 'tract_minority_population_percent',
 'ffiec_msa_md_median_family_income',
 'tract_to_msa_income_percentage',
 'tract_owner_occupied_units',
 'tract_one_to_four_family_homes',
 'tract_median_age_of_housing_units']

In [23]:
df.shape

(1047439, 99)

In [24]:
colunas_analise = [
    "activity_year",
    "state_code",
    "county_code",
    "derived_loan_product_type",
    "derived_dwelling_category",
    "action_taken",
    "loan_type",
    "loan_purpose",
    "loan_amount",
    "loan_to_value_ratio",
    "interest_rate",
    "property_value",
    "income",
    "debt_to_income_ratio",
    "loan_term",
    "occupancy_type"
]

In [25]:
df_analise.head()

,activity_year,state_code,county_code,derived_loan_product_type,derived_dwelling_category,action_taken,loan_type,loan_purpose,loan_amount,loan_to_value_ratio,interest_rate,property_value,income,debt_to_income_ratio,loan_term,occupancy_type
0,2024,FL,12031.0,VA:First Lien,Single Family (1-4 Units):Site-Built,3,3,31,535000.0,97.818,NaN,555000,NaN,NaN,360,1
1,2024,FL,12107.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,3,1,32,85000.0,80,NaN,115000,39.0,20%-<30%,360,1
2,2024,FL,12109.0,FHA:First Lien,Single Family (1-4 Units):Site-Built,1,2,1,515000.0,96.5,5.75,525000,175.0,50%-60%,360,1
3,2024,FL,12031.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,1,1,1,535000.0,73.197,6.625,735000,340.0,43,360,3
4,2024,FL,12031.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,4,1,32,215000.0,NaN,NaN,NaN,102.0,NaN,360,1

In [26]:
df_analise = df[colunas_analise].copy()

In [27]:
df_analise.info()

<class 'pandas.DataFrame'>
RangeIndex: 1047439 entries, 0 to 1047438
Data columns (total 16 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   activity_year              1047439 non-null  int64
 1   state_code                 1047439 non-null  str
 2   county_code                1040756 non-null  float64
 3   derived_loan_product_type  1047439 non-null  str
 4   derived_dwelling_category  1047439 non-null  str
 5   action_taken               1047439 non-null  int64
 6   loan_type                  1047439 non-null  int64
 7   loan_purpose               1047439 non-null  int64
 8   loan_amount                1047439 non-null  float64
 9   loan_to_value_ratio        668569 non-null   object
 10  interest_rate              637452 non-null   object
 11  property_value             812798 non-null   object
 12  income                     869812 non-null   float64
 13  debt_to_income_ratio       654724 non-null   str
 14  loan_term                  1032880 non-null  object
 15  occupancy_type             1047439 non-null  int64
dtypes: float64(3), int64(5), object(4), str(4)
memory usage: 127.9+ MB

In [28]:
qtd_nulos = df_analise["county_code"].isnull().sum()

percentual_nulos = df_analise["county_code"].isnull().mean() * 100

print(qtd_nulos)
print(percentual_nulos)

6683
0.6380323818379877

In [29]:
df_analise.isnull().mean().sort_values(ascending=False) * 100

interest_rate                39.141850
debt_to_income_ratio         37.492875
loan_to_value_ratio          36.171080
property_value               22.401400
income                       16.958219
loan_term                     1.389962
county_code                   0.638032
activity_year                 0.000000
loan_purpose                  0.000000
loan_type                     0.000000
action_taken                  0.000000
derived_dwelling_category     0.000000
derived_loan_product_type     0.000000
state_code                    0.000000
loan_amount                   0.000000
occupancy_type                0.000000
dtype: float64

In [30]:
df_analise["action_taken"].value_counts()

action_taken
1    476451
3    207409
4    146151
6    126090
5     56897
2     30893
8      2453
7      1095
Name: count, dtype: int64

In [31]:
# filtra somente esses registros
df_analise[df_analise["interest_rate"].isnull()]

,activity_year,state_code,county_code,derived_loan_product_type,derived_dwelling_category,action_taken,loan_type,loan_purpose,loan_amount,loan_to_value_ratio,interest_rate,property_value,income,debt_to_income_ratio,loan_term,occupancy_type
0,2024,FL,12031.0,VA:First Lien,Single Family (1-4 Units):Site-Built,3,3,31,535000.0,97.818,NaN,555000,NaN,NaN,360,1
1,2024,FL,12107.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,3,1,32,85000.0,80,NaN,115000,39.0,20%-<30%,360,1
4,2024,FL,12031.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,4,1,32,215000.0,NaN,NaN,NaN,102.0,NaN,360,1
11,2024,FL,12035.0,VA:First Lien,Single Family (1-4 Units):Site-Built,4,3,1,365000.0,NaN,NaN,NaN,130.0,NaN,360,1
12,2024,FL,12037.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,4,1,32,455000.0,NaN,NaN,NaN,200.0,NaN,360,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1047429,2024,FL,12031.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,3,1,1,345000.0,97.0,NaN,365000.0,64.0,>60%,360.0,1
1047430,2024,FL,12001.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,4,1,1,165000.0,NaN,NaN,NaN,30.0,NaN,360.0,1
1047433,2024,FL,12127.0,Conventional:First Lien,Single Family (1-4 Units):Manufactured,3,1,31,155000.0,42.778,NaN,365000.0,47.0,38,360.0,1
1047434,2024,FL,12115.0,VA:First Lien,Single Family (1-4 Units):Site-Built,4,3,1,405000.0,NaN,NaN,NaN,90.0,NaN,360.0,1
1047436,2024,FL,12017.0,Conventional:First Lien,Single Family (1-4 Units):Site-Built,3,1,32,365000.0,84.63,NaN,425000.0,98.0,50%-60%,372.0,1

In [32]:
df_analise[df_analise["interest_rate"].isnull()]["action_taken"].value_counts()

action_taken
3    205812
4    144934
5     56683
7      1089
1       854
2       508
6       101
8         6
Name: count, dtype: int64

In [33]:
df_analise.dtypes

activity_year                  int64
state_code                       str
county_code                  float64
derived_loan_product_type        str
derived_dwelling_category        str
action_taken                   int64
loan_type                      int64
loan_purpose                   int64
loan_amount                  float64
loan_to_value_ratio           object
interest_rate                 object
property_value                object
income                       float64
debt_to_income_ratio             str
loan_term                     object
occupancy_type                 int64
dtype: object

In [34]:
df_analise["interest_rate"].value_counts(dropna=False)

interest_rate
NaN        409987
6.625       18403
6.625       17088
6.75        15608
6.5         13205
            ...
5.62400         1
4.62500         1
6.87400         1
6.99900         1
4.49000         1
Name: count, Length: 6024, dtype: int64

In [35]:
df_analise["interest_rate"].apply(type).value_counts()

interest_rate
<class 'float'>    724633
<class 'str'>      322806
Name: count, dtype: int64

In [36]:
df_analise[
    df_analise["interest_rate"].apply(lambda x: type(x) == str)
]["interest_rate"].value_counts()

interest_rate
6.625      18403
7.125      12865
6.875      10674
6.125      10373
Exempt      8934
           ...
5.62400        1
4.62500        1
6.87400        1
6.99900        1
4.49000        1
Name: count, Length: 3284, dtype: int64

In [37]:
pd.to_numeric(df_analise["interest_rate"], errors="coerce")

0            NaN
1            NaN
2          5.750
3          6.625
4            NaN
           ...
1047434      NaN
1047435    6.125
1047436      NaN
1047437    6.750
1047438    4.875
Name: interest_rate, Length: 1047439, dtype: float64

In [38]:
df_analise["interest_rate_exempt"] = (
    df_analise["interest_rate"] == "Exempt"
)

In [39]:
df_analise["interest_rate"] = pd.to_numeric(
    df_analise["interest_rate"],
    errors="coerce"
)

In [40]:
df_analise["interest_rate"].dtype

dtype('float64')

In [41]:
df_analise["interest_rate_exempt"] = (
    df["interest_rate"] == "Exempt"
)

In [42]:
df_analise["interest_rate_exempt"].value_counts()

interest_rate_exempt
False    1038505
True        8934
Name: count, dtype: int64

In [43]:
df_analise["property_value"].apply(type).value_counts()

property_value
<class 'float'>    609216
<class 'str'>      397263
<class 'int'>       40960
Name: count, dtype: int64

In [45]:
df_analise[
    df_analise["property_value"].apply(lambda x: type(x) == str)
]["property_value"].value_counts()

property_value
355000      11105
305000      10412
325000      10283
375000       9667
315000       9631
            ...
12405000        1
41905000        1
26055000        1
29805000        1
26755000        1
Name: count, Length: 1013, dtype: int64

In [46]:
property_convertido = pd.to_numeric(
    df_analise["property_value"],
    errors="coerce"
)

In [47]:
property_convertido.isnull().sum()

np.int64(243576)

In [48]:
df_analise["property_value"].isnull().sum()

np.int64(234641)

In [49]:
df_analise["property_value"].notnull() & property_convertido.isnull()

0          False
1          False
2          False
3          False
4          False
           ...
1047434    False
1047435    False
1047436    False
1047437    False
1047438    False
Name: property_value, Length: 1047439, dtype: bool

In [50]:
df_analise[
    df_analise["property_value"].notnull()
    & property_convertido.isnull()
]["property_value"].value_counts()

property_value
Exempt    8935
Name: count, dtype: int64

In [51]:
df_analise["property_value_exempt"] = (
    df_analise["property_value"] == "Exempt"
)

In [52]:
df_analise["property_value"] = pd.to_numeric(
    df_analise["property_value"],
    errors="coerce"
)

In [53]:
print(df_analise["property_value"].dtype)
print(df_analise["property_value_exempt"].value_counts())

float64
property_value_exempt
False    1038504
True        8935
Name: count, dtype: int64

In [54]:
df_analise["loan_to_value_ratio"].apply(type).value_counts()

loan_to_value_ratio
<class 'float'>    709189
<class 'str'>      338250
Name: count, dtype: int64

In [56]:
df_analise[df_analise["loan_to_value_ratio"]. apply(lambda x:type(x) == str)
]["loan_to_value_ratio"].value_counts()

loan_to_value_ratio
80          14277
96.5        13106
80.00000    13022
96.50000     9705
Exempt       8935
            ...
21.678          1
16.817          1
101.714         1
70.560          1
74.529          1
Name: count, Length: 90006, dtype: int64

In [58]:
df_analise["loan_to_value_ratio_exempt"] = (
    df_analise["loan_to_value_ratio"] == "Exempt"
)

In [59]:
df_analise["loan_to_value_ratio_exempt"].value_counts()

loan_to_value_ratio_exempt
False    1038504
True        8935
Name: count, dtype: int64

In [ ]:
df_analise["loan_to_value_ratio"] = pd.to_numeric(
    df_analise["loan_to_value_ratio"],
    errors="coerce"
)

In [61]:
df_analise["loan_to_value_ratio"] = pd.to_numeric(
    df_analise["loan_to_value_ratio"],
    errors="coerce"
)

In [62]:
df_analise["loan_to_value_ratio"].dtype

dtype('float64')

In [63]:
df_analise["loan_term"].apply(type).value_counts()

loan_term
<class 'str'>      524955
<class 'int'>      335872
<class 'float'>    186612
Name: count, dtype: int64

In [64]:
df_analise[
    df_analise["loan_term"].apply(lambda x: type(x) == str)
]["loan_term"].value_counts()

loan_term
360    402833
240     26895
180     25901
300     24430
120     15267
        ...
89          1
113         1
139         1
31          1
25          1
Name: count, Length: 479, dtype: int64

In [65]:
df_analise["loan_term"] = pd.to_numeric(
    df_analise["loan_term"],
    errors="coerce"
)

In [66]:
df_analise["loan_term"].dtype

dtype('float64')

In [67]:
df_analise["debt_to_income_ratio"].value_counts(dropna=False).head(20)

debt_to_income_ratio
NaN         392715
50%-60%      88096
30%-<36%     72493
>60%         68485
20%-<30%     64236
49           40396
<20%         33315
44           27636
48           25960
42           25175
47           23639
43           23013
46           22333
45           22118
41           21210
40           20304
39           18863
38           17184
37           16207
36           15126
Name: count, dtype: int64

In [68]:
valor_total = df_analise["loan_amount"].sum()

valor_medio = df_analise["loan_amount"].mean()

valor_mediano = df_analise["loan_amount"].median()

print(valor_total)
print(valor_medio)
print(valor_mediano)

342363895000.0
326858.0747900355
255000.0

In [69]:
df_analise["loan_amount"].describe()

count    1.047439e+06
mean     3.268581e+05
std      2.567367e+06
min      5.000000e+03
25%      1.150000e+05
50%      2.550000e+05
75%      3.850000e+05
max      1.050005e+09
Name: loan_amount, dtype: float64

In [70]:
df_analise.nlargest(10, "loan_amount")[
    ["loan_amount", "property_value", "loan_to_value_ratio", "action_taken"]
]

         loan_amount  property_value  loan_to_value_ratio  action_taken
445298  1.050005e+09    6.267050e+08                 76.7             1
445297  9.455050e+08    1.312715e+09                 72.0             1
30665   8.440550e+08    9.950000e+05                  NaN             6
30667   6.150050e+08    1.535000e+06                  NaN             6
30633   5.500050e+08    8.550000e+05                  NaN             6
531646  5.000250e+08             NaN                  NaN             4
30605   5.000050e+08    1.105000e+06                  NaN             6
30621   4.375050e+08    6.250000e+05                  NaN             6
911771  3.720050e+08    5.250000e+05                  NaN             6
435213  3.442250e+08    4.635000e+06                 67.0             1

In [71]:
df_analise.groupby("action_taken")["loan_amount"].agg(
    ["count", "mean", "median", "max"]
)

               count           mean    median           max
action_taken
1             476451  359279.936447  275000.0  1.050005e+09
2              30893  271963.389765  195000.0  3.000500e+07
3             207409  238555.728054  155000.0  2.787150e+08
4             146151  358753.925734  275000.0  5.000250e+08
5              56897  246547.357506  165000.0  3.323550e+08
6             126090  362369.180744  315000.0  8.440550e+08
7               1095  273630.136986  225000.0  3.755000e+06
8               2453  347914.798206  295000.0  1.112500e+07